# Run:
# dconf load /org/gnome/ < dconf_org_gnome.ini

[desktop/input-sources]
sources=[('xkb', 'au')]
xkb-options=['ctrl:nocaps']

[desktop/wm/keybindings]
switch-to-workspace-1=['<Super>1']
switch-to-workspace-2=['<Super>2']
switch-to-workspace-3=['<Super>3']
switch-to-workspace-4=['<Super>4']
switch-to-workspace-5=['<Super>5']
switch-to-workspace-6=['<Super>6']

[desktop/wm/preferences]
num-workspaces=6
workspace-names=['code', 'deploy', 'term', 'llm', 'web', 'misc']

[settings-daemon/plugins/media-keys]
terminal=['<Super>t']

[mutter]
dynamic-workspaces=false
edge-tiling=false

[mutter/keybindings]
toggle-tiled-left=@as []
toggle-tiled-right=@as []

[shell/keybindings]
switch-to-application-1=@as []
switch-to-application-2=@as []
switch-to-application-3=@as []
switch-to-application-4=@as []
switch-to-application-5=@as []
switch-to-application-6=@as []
switch-to-application-7=@as []
switch-to-application-8=@as []
switch-to-application-9=@as []

[shell/extensions/dash-to-dock]
app-hotkey-1=@as []
app-hotkey-2=@as []
app-hotkey-3=@as []
app-hotkey-4=@as []
app-hotkey-5=@as []
app-hotkey-6=@as []
app-hotkey-7=@as []
app-hotkey-8=@as []
app-hotkey-9=@as []
app-hotkey-10=@as []
dock-fixed=false
hot-keys=false

[shell/extensions/resource-monitor]
extensionposition='right'
cpucolors=['70 1 0.6392157077789307 0.2823529541492462', '85 0.9647058844566345 0.3803921639919281 0.3176470696926117']
thermalcpucolors=['60 1 0.6392157077789307 0.2823529541492462', '80 0.9647058844566345 0.3803921639919281 0.3176470696926117']
ramcolors=['10 1 0.6392157077789307 0.2823529541492462', '13 0.9647058844566345 0.3803921639919281 0.3176470696926117']
ramunit='numeric'
ramunitmeasure='auto'
thermalcputemperaturestatus=true
cpufrequencystatus=false
cpuloadaveragestatus=false
diskspacestatus=false
diskstatsstatus=false
netautohidestatus=false
netethstatus=false
netwlanstatus=false
thermalgputemperaturestatus=false

[shell/extensions/tiling-assistant]
enable-tiling-popup=false

[shell/extensions/ding]
show-home=false
