# Set proper terminal settings for colour rendering, particularly in vim
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"

# Rename window titles automatically
setw -g automatic-rename

# Reorder window index numbers when a window is deleted
set-option -g renumber-windows on

# Start window index numbers from 1 instead of 0
set -g base-index 1
setw -g pane-base-index 1

# Status bar
# set -g status-left ''
# set -g status-left-length 0
# set -g status-right '%a %d/%m/%Y %H:%M'
# set -g status-right-length 20
# set -g status-style fg=colour8
# set -g pane-border-style fg=colour240
# set -g pane-active-border-style fg=colour243
# set-window-option -g window-status-current-style fg=colour10
