# Enable mouse mode
setw -g mouse on

# Set proper terminal settings for colour rendering, particularly in vim
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"

# Rename window titles automatically
setw -g automatic-rename

# Reorder window index numbers when a window is deleted
set-option -g renumber-windows on

# Start window index numbers from 1 instead of 0
set -g base-index 1
setw -g pane-base-index 1

# Put window list in center
set-option -g status-justify centre

# Status bar
set -g status-fg 'white'
set -g status-bg 'colour238'
setw -g window-status-current-style 'fg=colour10,bold'
set -g pane-border-style 'fg=colour243'
set -g pane-active-border-style 'fg=colour10'

