# Disable newline between prompts
add_newline = false

# Disable multi-line prompts (we force this later anyways)
[line_break]
disabled = true

# Update prompt character on success and error
[character]
success_symbol = "[\n|](bold gray)" # = "[\n::](bold green)"
error_symbol   = "[\n|](bold red)" # = "[\n!!](bold red)"

# Show machine username
[username]
style_user  = "bold green"
disabled    = false
show_always = true

# Show current timestamp
[time]
disabled        = true
format          = '[ \[$time\] ]($style)'
time_format     = "%T"
utc_time_offset = "10"
time_range      = "00:00:00-23:59:59"

# Command duration indicator
[cmd_duration]
style = "bold bright-black"

# Truncate cwd shown fish-style
[directory]
style = "bold blue"
fish_style_pwd_dir_length = 1
