# Load environment variables, aliases, functions and prompt
source $HOME/dotfiles/zsh/zshenv
source $HOME/dotfiles/zsh/zsh_variables
source $HOME/dotfiles/zsh/zsh_aliases
source $HOME/dotfiles/zsh/zsh_functions
source $HOME/dotfiles/zsh/zsh_prompt
source $HOME/dotfiles/zsh/zsh_plugins

# Enable zmv
autoload zmv

# Set emacs keybindings
set -o emacs

# Node version manager
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Active oh-my-zsh plugins
plugins=(
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
    nvm
)

eval $(thefuck --alias)

# Load oh-my-zsh
source $ZSH/oh-my-zsh.sh

# opam configuration
[[ ! -r /home/james/.opam/opam-init/init.zsh ]] || source /home/james/.opam/opam-init/init.zsh  2>&1 /dev/null
