source $HOME/dotfiles/zsh/zsh_variables
source $HOME/dotfiles/zsh/zsh_aliases
source $HOME/dotfiles/zsh/zsh_prompt
source $HOME/dotfiles/zsh/zsh_plugins
source $HOME/dotfiles/zsh/zshenv

unsetopt beep
autoload zmv

plugins=(
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh
